### ISSUE TITLE
Segmentation fault when PGHOST env is provided.

### ISSUE THREAD

**Issue by tonila** [brianc/node-pg-native#68] opened 2018-04-16 12:52 UTC
Hi,

I'm getting "Segmentation fault" if I run node-pg-native with PGHOST env.

Here is my code:

```
var Client = require('pg-native')

var client = new Client();
client.connect(function(err) {
  if(err) console.log(err);
  console.log('connected')
})
```

And this is how I run it:

```
$ PGHOST=127.0.0.1 PGDATABASE=somedb PGPORT=5432 PGUSER=dbuser PGPASSWORD=secretpass node pgtest.js
Segmentation fault
```

If I drop PGHOST parameter, it connects nicely. 

Also tested with node-postgres, and it woks fine, when native wrapper is not used.

testing with:
Debian 9
node.js v8.11.1
PostgreSQL 9.6.7 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

**Comment by charmander** [comment] 2018-05-31 17:48
Duplicate of #70

**Closed by charmander** 2018-05-31 17:48 UTC
